name: Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_build_template.yml@common-files
    with:
      package_name: http_exceptions

  publish_test_pypi:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_publish_template.yml@common-files
    with:
      test_pypi_url: https://test.pypi.org/project/http-exceptions/
    secrets:
      testpypi_token: ${{ secrets.TESTPYPI_TOKEN }}
