name: Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: DeveloperRSquared/.github/.github/workflows/TEMPLATE.yml@common-files
    with:
      username: rikhil
