name: Deploy
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: src

env:
  DOCKER_IMAGE: http-exceptions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build
        run: docker build --tag ${DOCKER_IMAGE} .

      - name: Check code style (black)
        run: docker run --rm --volume $(pwd)/pyproject.toml:/app/pyproject.toml --env CI=true --entrypoint python ${DOCKER_IMAGE} -m black --config /app/pyproject.toml --check .

      - name: Check code style (flake8)
        run: docker run --rm --volume $(pwd)/.flake8:/app/.flake8 --env CI=true --entrypoint python ${DOCKER_IMAGE} -m flake8 --config /app/.flake8

      - name: Check lint (pylint)
        run: docker run --rm --volume $(pwd)/pyproject.toml:/app/pyproject.toml --env CI=true --entrypoint python ${DOCKER_IMAGE} -m pylint --rcfile /app/pyproject.toml http_exceptions tests

      - name: Check typing (mypy)
        run: docker run --rm --volume $(pwd)/mypy.ini:/app/mypy.ini --env CI=true --entrypoint python ${DOCKER_IMAGE} -m mypy --config-file /app/mypy.ini http_exceptions tests

      - name: Run tests (pytest)
        run: docker run --rm --env CI=true --entrypoint python ${DOCKER_IMAGE} -m pytest --capture=no --log-cli-level=INFO
