name: Publish to TestPyPI

on:
  push:
    paths:
      # NOTE: this is a proxy for a version update
      - 'pyproject.toml'
      - '!docs/**'
    branches:
      - main

jobs:
  publish_test_pypi:
    uses: DeveloperRSquared/.github/.github/workflows/python_package_publish_template.yml@common-files
    with:
      environment: TestPyPI
      pypi_url: https://test.pypi.org/project/http-exceptions/
      should_publish_to_test_pypi: true
      should_upload_coverage_to_codecov: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      pypi_token: ${{ secrets.TESTPYPI_TOKEN }}
